services:
  backend:
    image: arnaumm2/easyeat-backend:v0.9.0
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/easyeat-db
    depends_on:
      - mongodb

  backoffice:
    image: arnaumm2/easyeat-backoffice:v0.9.0
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
      - API_URL=http://backend:3000
    depends_on:
      - backend

  web-client:
    image: arnaumm2/easyeat-web:v0.9.0
    ports:
      - "8080:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
